replicaCount: 1

image:
  repository: kodekloud/examplevotingapp_result:v1
  pullPolicy: IfNotPresent
service:
  name: result
  type: NodePort
  port: 80
  nodePort: 30005
  containerPort: 80
imagePullSecrets: []

deployment:
  name: result
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

container:
  name: result
